### PR TITLE
feat: add bug/feature templates, remove spike template

### PR DESCRIPTION
**Pull request by alexveecle**
## Intent

Rearrange issue templates.

## Description

The spike template was not working (it's not in the proper place). Removing it. We also don't want it on all public repos. Adding GH's default bug/feature templates, so when we add the spike template to private repos it doesn't look "alone".

## Checklist

- na Documentation in README, crate, module, function and/or other locations added/adapted.
- na New tests added and/or existing tests adapted.
- [x] PR is limited to a single logical change.
- [x] At least the first commit has a clear title and a descriptive message containing reasoning for the change. This will be included in the final commit message after squashing and merging.

### CODE REVIEW

**Comment by alexveecle** [comment]
I created a template using the web ui, and it used this path. The previous template apparently is not working.

**Review by arctic-alpaca — CHANGES_REQUESTED** [review]
If I understand issue templates correctly, this will be offered to anyone creating an issue for any of our repositories. I'd like to only serve this template if there is also one for bug reports / feature requests.

**Review by vE5li — APPROVED** [review]

**Comment by alexveecle** [comment]
Good point; there's also the thing that public repositories perhaps should not get this spike?

GitHub has some default templates, I can add them to this PR and we can decide how to move forward, so we don't have the spike template as the *only* template.

(But in any case, we should do something- the current template is not available, so that's weird.)

**Comment by arctic-alpaca** [comment]
I agree that having it available would be better. If it is one of multiple templates that also make sense for externals, I'd be happy to approve.

**Comment by alexveecle** [comment]
I just copied the default bug/feature request templates that GItHub provides. This way *everyone* would get the three issue templates. Having the spike template publicly available might not make a ton of sense, the only alternatives I believe we could do are:

* Have a separate org for public repos. (This wouldn't be so strange, although I think it would add considerable management overhead.)
* Keep a template in company-rules, or a procedure or something.
* Remove *all* templates from `.github`.

I have no strong opinion. In general I'm not a huge fan of templates, so I wouldn't mind going with "no templates at all".

**Comment by arctic-alpaca** [comment]
We can also just move the spike template to the `nos` repo, since we use a monorepo and most/all of our spikes are probably centered around nos, this could make sense.

**Comment by alexveecle** [comment]
That is easier, I'll do that. Hopefully we can leave the bug/feature templates here, have the spike template on the nos repository... and that will work properly (you get the three templates on the nos repo, two on the rest).

**Review by arctic-alpaca — APPROVED** [review]

**Comment by HectorMRC** [comment]
I dislike the idea of having the Spike template at `nos`. I would rather prefer to have a template repository or something where to put our generic stuff.

**Comment by alexveecle** [comment]
> At least my original idea was not to put it here to make it automatically available, but to keep all templates in the same place.

Oh, I didn't know about this. I kinda like this idea. But then, it is not very discoverable (I wanted to open a spike; I knew there was a template so I came looking to this repository, but otherwise I would not have found it).

I don't know, given that we cannot be granular with some templates showing in some repos and which not, I think we're making an excessive effort at refining this.

Esp. because I'm not a huge fan of issue templates, I think I'll defer working on this and close this PR and <https://github.com/veecle/nos/pull/100>. Perhaps we should have a quick discussion about different options and what do we want to do, although given that I don't think that issue templates give us huge benefits right now, I would not invest a lot of time here.

**Pull request closed without merging**
